### ISSUE TITLE
How would this component intercept traffic?

### ISSUE THREAD

**Issue by beemarie** [beemarie/async-component#3]
One option is to intercept all traffic, although preferably, this component would only receive requests with a Prefer:respond-async header, so that we're not adding a hop to every request.

We could update the KIngress to send requests to myapp.11.111.111.11.xip.io with async header to this component, but this requires changes to /serving.

**Comment by beemarie** [comment]
Right now, we do have a proxy that checks the header, but it’s unclear to me how to route traffic coming into the cluster to this proxy.

When a request comes in to our service: curl myservice.11.111.11.11.xip.io there’s a virtual service (in istio) created by knative that looks for this route & sends traffic to something like this: myservice-v9.default.svc.cluster.local

 We can’t just create a new virtual service to intercept * or *.11.111.11.11.xip.io because it appears that when virtual service hosts are conflicting, istio begins with the most specific host.

**Comment by beemarie** [comment]
We currently create a new vs like this:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: async-vs
spec:
  hosts:
  - "perftest.default.52.116.240.92.xip.io"
  gateways:
  - knative-serving/cluster-local-gateway
  - knative-serving/knative-ingress-gateway
  http:
  - match:
    - headers:
        Prefer:
          exact: respond-async
      ignoreUriCase: true
    route:
    - destination:
        host: producer-service.default.svc.cluster.local #producer-service #async-producer.default.52.116.240.92.xip.io # Destination service, must match service name
        port:
            number: 80 # Post of service, must match service port
```
When hosts match, istio prioritizes the oldest VS, so this must be created before the service is created in knative.
